apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmpest-website
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
      tier: web
  template:
    metadata:
      labels:
        app: webserver
        tier: web
    spec:
      containers:
      - name: webserver-container
        image: tmpest/go-website:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_RECAPTCHA_SECRET
          value: "6Lcxg9sUAAAAAPtpL02zxFYJmNZfed7qYBPLS6BG"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tmpest-website
  annotations:
    kubernetes.io/ingress.global-static-ip-name: tmpest-website-static-ip
    networking.gke.io/managed-certificates: tmpest-website-certificate
  labels:
    app: webserver
spec:
  backend:
    serviceName: tmpest-website-backend
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: tmpest-website-backend
    labels:
      pp: webserver
spec:
  type: NodePort
  selector:
    app: webserver
    tier: web
  ports:
    - name: my-https-port
      port: 443
      targetPort: 8443
    - name: my-http-port
      port: 80
      targetPort: 8080
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
    name: tmpest-website-certificate
spec:
  domains:
    - tmpest.com
    - www.tmpest.com
             
    