apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tmpest-website
  annotations:
    kubernetes.io/ingress.global-static-ip-name: tmpest-website-static-ip
  labels:
    app: webserver
spec:
  backend:
    serviceName: tmpest-website-backend
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tmpest-website-backend
  labels:
    app: webserver
spec:
  type: NodePort
  selector:
    app: webserver
    tier: web
  ports:
  - port: 8080
    targetPort: 8080